fixed vertical scrolling on mobile issue with 3 steps.
gbrlsnchs/material2-carousel pull request #22
Opened 2019-07-28 18:44 UTC by chriswnewman

This PR fixes vertical scrolling issues on mobile.

1) Added a DI provider with an instance of HammerGestureConfig per https://github.com/angular/angular/issues/10541#issuecomment-300761387

2) App Modules need to import CarouselModule using static forRoot() method
- https://alligator.io/angular/providers-shared-modules/ 

3) Ignore vertical pans in the onPan function, where y velocity is greater than x velocity.
 - https://github.com/angular/angular/issues/10541#issuecomment-346539242

2019-09-11 20:39 UTC, gbrlsnchs requested changes

2019-09-11 20:39 UTC, gbrlsnchs commented on projects/carousel/src/lib/carousel.component.ts
> +      // console.log('y velocity is greater, ignoring');
Could you remove this line?

2019-09-11 20:39 UTC, gbrlsnchs commented on projects/demo/src/app/app.module.ts
> +    MatCarouselModule.forRoot(),
If `forRoot` is the way to import this module now, maybe it should be a nice idea to explain that in README.

2019-09-12 18:24 UTC, chriswnewman commented on projects/carousel/src/lib/carousel.component.ts
> +      // console.log('y velocity is greater, ignoring');
Removed line.

2019-09-12 18:24 UTC, chriswnewman commented on projects/demo/src/app/app.module.ts
> +    MatCarouselModule.forRoot(),
Updated README.md

2019-09-27 17:25 UTC, merged